[base]
name = conntility
testdeps =
    pytest

[pytest]
minversion = 6.0
testpaths =
    tests

[tox]
envlist =
    {py310,py311,py312}
    check-dist
    lint
    coverage

[testenv]
deps = {[base]testdeps}
commands = pytest --basetemp={envtmpdir} {posargs}

[testenv:check-dist]
deps = twine
       build
commands =
    rm -rf {toxinidir}/dist
    python -m build
    twine check {toxinidir}/dist/*
allowlist_externals = rm

[testenv:lint]
deps =
    pycodestyle
commands =
    pycodestyle {[base]name} --exclude tests

[testenv:coverage]
deps =
    {[base]testdeps}
    coverage
commands =
    coverage run --source={[base]name} -m pytest tests {posargs}
    coverage report --show-missing
    coverage xml

[pycodestyle]
max-line-length = 120

[pydocstyle]
convention = google

[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312, check-dist, lint, coverage
